name: Go CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'  # 使いたいGoのバージョンに変更

      # gofmt check
      - name: Run gofmt
        run: |
          if [ -n "$(gofmt -l .)" ]; then
            echo "gofmt found issues:"
            gofmt -d .
            exit 1
          fi

      # go vet check
      - name: Run go vet
        run: go vet ./...

      # golangci-lint
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: run ./...